# Generated by Django 2.1.7 on 2019-06-24 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100, verbose_name='评论内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
        ),
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('data_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='上传数据ID')),
                ('data_type', models.CharField(max_length=256, verbose_name='数据类型')),
                ('data_name', models.CharField(max_length=256, verbose_name='数据名称')),
                ('data_path', models.CharField(max_length=256, verbose_name='数据路径')),
                ('data_location', models.CharField(blank=True, max_length=256, null=True, verbose_name='数据上传位置')),
                ('data_province', models.CharField(blank=True, max_length=256, null=True, verbose_name='数据上传省份')),
                ('data_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据上传时间')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='DomainInfo',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False, verbose_name='领域ID')),
                ('domain_name', models.CharField(max_length=40, verbose_name='领域名')),
            ],
        ),
        migrations.CreateModel(
            name='IssueInfo',
            fields=[
                ('issue_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='issueID')),
                ('title', models.CharField(max_length=100, verbose_name='issue题目')),
                ('description', models.CharField(max_length=280, verbose_name='issue问题描述')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='issue发布时间')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False, verbose_name='模型ID')),
                ('model_name', models.CharField(max_length=30, verbose_name='模型名字')),
                ('model_introduction', models.TextField(max_length=5000, verbose_name='模型介绍')),
                ('is_unloaded', models.BooleanField(default=False, verbose_name='自定义与否')),
                ('model_path', models.CharField(max_length=256, verbose_name='模型路径')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.IntegerField(default=0, verbose_name='审核情况')),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.DataInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, verbose_name='项目ID')),
                ('projection_name', models.CharField(max_length=100, verbose_name='项目名字')),
                ('projection_introduction', models.TextField(max_length=5000, verbose_name='项目介绍')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('model', models.CharField(default='null', max_length=256, verbose_name='模型路径')),
                ('projection_image', models.CharField(max_length=256, null=True, verbose_name='项目缩略图')),
                ('need_data', models.CharField(max_length=4096, null=True, verbose_name='项目所需数据')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.DomainInfo')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.IssueInfo')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.ProjectInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='权限登记时间')),
                ('authority', models.IntegerField(default=3, verbose_name='用户参与权限')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.ProjectInfo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='projectimage',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.ProjectInfo'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.IssueInfo'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.UserInfo'),
        ),
    ]
