# Generated by Django 2.1.7 on 2019-07-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='participants_num',
            field=models.IntegerField(default=0, verbose_name='参与人数'),
        ),
    ]
