# Generated by Django 2.1.7 on 2019-07-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_projectinfo_participants_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
