# Generated by Django 2.1.7 on 2019-07-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_projectinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='weight',
            field=models.FloatField(default=-100, verbose_name='排序权重'),
        ),
    ]
